### ISSUE TITLE
What is the significance of this project compared to using antlr4

### ISSUE THREAD

**Issue by itviewer** [chipsalliance/tree-sitter-firrtl#1]
antlr4 can generate [lots of ](https://github.com/antlr/antlr4/tree/master/runtime)target language parser.
what are the advantages of tree-sitter compared to antlr4?
If we want to migrate firrtl tools to pure JavaScript, like you asked in https://github.com/freechipsproject/firrtl/issues/1356
I think the best way is to use antlr4 to generate JavaScript lexer and parser, compared with the java target, they have similar APIs, so it maybe relatively easy to migrate firrtl related algorithms to pure JavaScript.

**Comment by drom** [comment]
This project is FIRRTL grammar for [tree-sitter](https://tree-sitter.github.io/tree-sitter) parser that have some properties, that ANTLR4 lucks:
* pure C, not JavaScript
* incremental parser (so it can reparse only changes in the source)
* non-failing parser, so it can find multiple errors
* easy to integrate with modern IDEs based on Atom and VS Code

**Comment by itviewer** [comment]
thanks!
